services:
  postgres:
    image: postgres
    container_name: library-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - library-data:/var/lib/postgresql/data


volumes:
  library-data:
    driver: local