spring:
  application:
    name: library
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      default_batch_fetch_size: ${application.pagination.max-page-size}
      jdbc:
        batch_size: 20
      order_inserts: true
      order_updates: true
  liquibase:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}


frontend:
  url: ${FRONTEND_URL:http://localhost:4200}


server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|192\\.168\\.\\d{1,3}\\.\\d{1,3}|169\\.254\\.\\d{1,3}\\.\\d{1,3}|127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|172\\.1[6-9]\\.\\d{1,3}\\.\\d{1,3}|172\\.2[0-9]\\.\\d{1,3}\\.\\d{1,3}|172\\.3[0-1]\\.\\d{1,3}\\.\\d{1,3}

application:
  pagination:
    default-page-size: 20
    max-page-size: 50
    min-page-size: 1
  recommendations:
    trigger:
      count: 50
      days: 14
    rebuild:
      batch-size: 100
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration: 86400000
      refresh-token-expiration: 172800000
      cookie-name: ${JWT_COOKIE_NAME:jwt}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}
