spring:
  config:
    activate:
      on-profile: prod

logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 500MB
      max-history:
  file:
    name: ${LOG_FILE_PATH:application.log}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"