spring:
  config:
    activate:
      on-profile: dev

  jpa:
    properties:
      hibernate:
        generate_statistics: false
        show_sql: false
        format_sql: false
  liquibase:
    contexts: dev


logging:
  level:
    org.example.library: DEBUG